const path = require('node:path');
const express = require("express")

//Not sure what process.env.PORT is for. I think it is for hosting oh Heroku? 
//Also the port for Heroku is 3001, I changed it for 8080
const PORT = process.env.PORT || 8080

const app = express()

//tell Node which files to serve 
//specifically we will serve from our `build` generated by React
//if a GET request comes in that is not handled by our /api route, our server will respond with our React app.
app.use(express.static(path.resolve(__dirname, "../client/build")))

//Create a route. THIS HAS TO BE ABOVE app.listen. Why tho? Probably because we want to configure routes, before listeting (running)
app.get("/hello", (req, res) => {
    res.json({message: "Hello world"})
})

//All other routes (GET requests) will return to the React app 
app.get("*", (req, res) => {
    res.sendFile(path.resolve(__dirname, "../client/build", "index.html"))
})

//I think this configures the port we are listeting to. The arrow function runs on connection?
app.listen(PORT, () => {
    console.log(`Server Listening on ${PORT}`)
})
